### PR TITLE
impersonate: add `chrome_126`

### PR DESCRIPTION
**Pull request by deedy5**
## Summary by CodeRabbit

- **New Features**
  - Introduced support for Chrome version 126 in the impersonation settings, providing improved SSL configuration and HTTP headers for better compatibility and security.

### CODE REVIEW

**Comment by deedy5** [comment]
Everything seems to be normal, but when checking on https://tls.peet.ws/api/all "accept-language: en-US,en;q=0.9" for some reason is not at the end (as in the browser), but before 'sec-ch-ua:...'.

**Comment by 0x676e67** [comment]
The order of the request header is similar to that of a dictionary. It is not set in the order of insertion. We are considering how to solve this problem.

**Comment by 0x676e67** [comment]
You are just a response processing. What we need to consider is the headers of request.

**Comment by 0x676e67** [comment]
It depends on an http library. Modifying it will make many libraries difficult to be compatible.

**Comment by deedy5** [comment]
```rust
use http::HeaderMap;

pub struct OrderedHeaderMap {
    inner: HeaderMap,
    order: Vec<String>,
}

impl OrderedHeaderMap {
    pub fn new() -> Self {
        OrderedHeaderMap {
            inner: HeaderMap::new(),
            order: Vec::new(),
        }
    }

    pub fn insert(&mut self, key: &str, value: impl IntoHeaderValue) -> Option<&HeaderValue> {
        let result = self.inner.insert(key, value.into());
        if let Some(value) = result {
            self.order.push(key.to_string());
        }
        result
    }

    pub fn remove(&mut self, key: &str) -> Option<HeaderValue> {
        if let Some(value) = self.inner.remove(key) {
            self.order.retain(|k| k!= key);
            return Some(value);
        }
        None
    }

    pub fn iter(&self) -> std::slice::Iter<'_, (&'static str, &'static str)> {
        self.order.iter().map(|key| (key.as_str(), self.inner.get(key)))
    }
}

impl Default for OrderedHeaderMap {
    fn default() -> Self {
        Self::new()
    }
}
```

**Comment by deedy5** [comment]
Look here https://github.com/hyperium/http/blob/f4e8c0c3159b18b8b7e4a6a3762c55528483d25a/src/header/mod.rs#L45-L50

**Comment by 0x676e67** [comment]
But it was not as expected

**Pull request merged**
